name: c-sharp
version: "4.0.1.5"
schema: 1
scm: github.com/pubnub/c-sharp
changelog: 
  - version: 4.0.1.5
    changes:
      - type: Improvement
        text: Refactored to handle thread blocking
  - version: 4.0.1.4
    changes:
      - type: Improvement
        text: Fix to support Xamarin.Android Pubnub SDK install using Visual Studio
  - version: 4.0.1.3
    changes:
      - type: Improvement
        text: Added code to handle presence interval event
      - type: Improvement
        text: Code refactor per CA2000 code analysis
  - version: 4.0.1.3-rc13
    changes:
      - type: Improvement
        text: Refactored to address false alert log and timeout messages.
  - version: 4.0.1.3-rc12
    changes:
      - type: Improvement
        text: Support for ASP.NET/MVC project template projects.
  - version: 4.0.1.3-rc11
    changes:
      - type: Improvement
        text: Replaced HttpClient with compatible lib for .net 4.5/4.61 to support VS 2013.
  - version: 4.0.1.3-rc10
    changes:
      - type: bug fix
        text: Comma encoding fix for multi channelgroups
      - type: bug fix
        text: Fixed channel remove from channelgroup
  - version: 4.0.1.3-rc9
    changes:
      - type: bug fix
        text: Message fix for history when timetoken=false.
  - version: 4.0.1.3-rc8
    changes:
      - type: improvement
        text: Added pn- prefix to default uuid.
  - version: 4.0.1.3-rc7
    changes:
      - type: bug fix
        text: pcl profile 111 subscribe message fix.
  - version: 4.0.1.3-rc6
    changes:
      - type: bug fix
        text: Timetoken fix for subscribed messages.
  - version: 4.0.1.3-rc5
    changes:
      - type: improvement and bug fix
        text: HttpClient to supported platforms. Fixed Unsubscribe issue.
  - version: 4.0.1.3-rc1
    changes:
      - type: improvement
        text: Derived classes for inline coding.
  - version: 4.0.1.2-rc1
    changes:
      - type: improvement
        text: Cipher typo, Origin change.
  - version: 4.0.1.0-rc1
    changes:
      - type: improvement
        text: initial v4 version.
features: 
  access:
    - ACCESS-GRANT
    - ACCESS-SECRET-KEY-ALL-ACCESS    
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  notify:
    - REQUEST-MESSAGE-COUNT-EXCEEDED
  push:
    - PUSH-ADD-DEVICE-TO-CHANNELS
    - PUSH-REMOVE-DEVICE-FROM-CHANNELS
    - PUSH-LIST-CHANNELS-FROM-DEVICE
    - PUSH-REMOVE-DEVICE
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
    - PRESENCE-HEARTBEAT
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
    - PUBLISH-ASYNC
    - PUBLISH-FIRE 
    - PUBLISH-REPLICATION-FLAG
    - PUBLISH-MESSAGE-TTL
  storage:
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
  time:
    - TIME-TIME
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
    - SUBSCRIBE-PUBLISHER-UUID
supported-platforms:
  - 
    version: Pubnub 'C#' 4.0.1.3
    platforms:
      - Windows 10 and up
      - Windows Server 2008 and up
    frameworks:
      - .Net Framework 3.5
      - .Net Framework 4.0
      - .Net Framework 4.5
      - .Net Framework 4.6.1
  - 
    version: PubnubPCL 'C#' 4.0.1.3
    platforms:
      - Xamarin.Android
      - Xamarin.iOS
      - Xamarin.Mac
      - Windows 10
      - Mac OS X 10 and up
      - Windows Server 2008 and up
    frameworks:      
      - Mono 4.8.0
      - PCL Profile 111
  - 
    version: PubnubUWP 'C#' 4.0.1.3
    platforms:
      - Windows Phone 10
      - Universal Windows Apps
      - Windows 10
